import { useState, useEffect, useRef } from 'react';
import {
  Brain,
  Heart,
  Sparkles,
  History,
  BarChart2,
  ArrowRight,
  Search,
  Trash2,
  Plus,
  BookOpen,
  Award,
  Info,
  Calendar,
  AlertCircle,
  CheckCircle2,
  Shield,
  HelpCircle,
  RotateCcw,
  Volume2,
  ChevronRight
} from 'lucide-react';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  Cell,
  Legend
} from 'recharts';
import { motion, AnimatePresence } from 'motion/react';
import { JournalEntry, Distortion, Reframing, ReframeResponse } from './types';

// Predefined emotions for easy multi-select chips
const PRESET_FEELINGS = [
  { label: 'Anxious', category: 'anxiety' },
  { label: 'Overwhelmed', category: 'anxiety' },
  { label: 'Tense', category: 'anxiety' },
  { label: 'Critically Judged', category: 'shame' },
  { label: 'Inadequate', category: 'shame' },
  { label: 'Pressured', category: 'shame' },
  { label: 'Defeated', category: 'hopeless' },
  { label: 'Hopeless', category: 'hopeless' },
  { label: 'Guilty', category: 'shame' },
  { label: 'Frustrated', category: 'anger' },
  { label: 'Angry', category: 'anger' },
  { label: 'Perfectionist-Tense', category: 'shame' },
];

const EXAMPLE_THOUGHTS = [
  {
    text: "I didn't answer that question properly in the meeting. Everyone probably thinks I'm completely unqualified and I'm going to get fired.",
    feelings: ["Anxious", "Inadequate", "Critically Judged", "Pressured"]
  },
  {
    text: "I missed my exercise routine today. I have absolutely no self-discipline, and I'll never be able to get in shape.",
    feelings: ["Defeated", "Guilty", "Perfectionist-Tense"]
  },
  {
    text: "My friend didn't reply to my text message immediately. They are probably annoyed with me and our friendship is falling apart.",
    feelings: ["Anxious", "Frustrated", "Hopeless"]
  }
];

// Initial historical data so the user enters with a pre-filled, beautiful dashboard
const INITIAL_ENTRIES: JournalEntry[] = [
  {
    id: 'entry-1',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    moodBefore: 2,
    moodAfter: 4,
    feelings: ['Anxious', 'Pressured'],
    originalThought: 'I am so behind on this project. Everybody else is working much faster, I will fail the review.',
    detectedDistortions: [
      { name: 'Catastrophizing', explanation: 'Assuming the absolute worst outcome (failing the review) based on short-term speed.' },
      { name: 'Social Comparison', explanation: 'Adverse feelings generated by rating yourself against other colleagues.' }
    ],
    allReframings: [
      { type: 'Balanced Fact-Check', text: 'I have successfully completed similar milestones before. Everyone works at different speeds, and my output quality has always met expectations.' },
      { type: 'Compassionate Action', text: 'It is okay to ask for extension or clarification if my workload feels unsustainable. Real progress happens in blocks.' },
      { type: 'Coping Reflection', text: 'Even if I receive critical remarks in the review, that is helpful feedback, not a catastrophic failure.' }
    ],
    chosenReframing: 'I have successfully completed similar milestones before. Everyone works at different speeds, and my output quality has always met expectations.'
  },
  {
    id: 'entry-2',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    moodBefore: 1,
    moodAfter: 3,
    feelings: ['Inadequate', 'Defeated'],
    originalThought: 'I made a typo in the presentation slides. I can never do anything right, I am totally incompetent.',
    detectedDistortions: [
      { name: 'Overgeneralization', explanation: 'Taking a single typo and declaring that you can "never do anything right".' },
      { name: 'All-or-Nothing Statements', explanation: 'Labeling yourself as "totally incompetent" based on a single small human slip-up.' }
    ],
    allReframings: [
      { type: 'Self-Compassionate Adjustment', text: 'A single typo is a natural human oversight, not a measure of my work value.' },
      { type: 'Balanced Alternative', text: 'I made one small mistake, but the structural core of the presentation was highly praised.' }
    ],
    chosenReframing: 'A single typo is a natural human oversight, not a measure of my work value.'
  }
];

export default function App() {
  // Navigation
  const [activeTab, setActiveTab] = useState<'reframe' | 'vault' | 'landscape'>('reframe');

  // Journal entries & history state
  const [entries, setEntries] = useState<JournalEntry[]>(() => {
    const saved = localStorage.getItem('mindmirror_entries');
    if (saved) {
      try { return JSON.parse(saved); } catch (e) { return INITIAL_ENTRIES; }
    }
    return INITIAL_ENTRIES;
  });

  // Reframe creation multi-step flow state
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1); // 1: Check-in, 2: Thought Dump, 3: Processing/AI, 4: Interactive shattering
  
  // Thought Check-in states
  const [moodBefore, setMoodBefore] = useState<number>(3);
  const [moodAfter, setMoodAfter] = useState<number>(4);
  const [selectedFeelings, setSelectedFeelings] = useState<string[]>([]);
  const [thought, setThought] = useState<string>('');

  // AI loading / Analysis response
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [aiResponse, setAiResponse] = useState<ReframeResponse | null>(null);
  const [sandboxMode, setSandboxMode] = useState<boolean>(false);

  // Active Interactive shatter states
  const [selectedDistortion, setSelectedDistortion] = useState<Distortion | null>(null);
  const [shatteredDistortions, setShatteredDistortions] = useState<string[]>([]);
  const [chosenReframingText, setChosenReframingText] = useState<string>('');
  const [customJournalNotes, setCustomJournalNotes] = useState<string>('');
  const [isShatterAnimated, setIsShatterAnimated] = useState<boolean>(false);

  // Vault/History Search & Filters
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [filterDistortion, setFilterDistortion] = useState<string>('All');
  const [filterFeeling, setFilterFeeling] = useState<string>('All');

  // Save entries to local storage
  useEffect(() => {
    localStorage.setItem('mindmirror_entries', JSON.stringify(entries));
  }, [entries]);

  // Loading statements runner
  const [loadingStateText, setLoadingStateText] = useState<string>('Initializing Mirror Analyzer...');
  useEffect(() => {
    if (!isLoading) return;
    const phrases = [
      'Focusing mirror focus...',
      'Mapping automatic neural patterns...',
      'Deconstructing linguistic frameworks...',
      'Sifting for cognitive distortion structures...',
      'Tracing emotional cognitive triggers...',
      'Designing comforting re-evaluation paths...',
      'Polishing realistic, comforting alternatives...'
    ];
    let i = 0;
    const interval = setInterval(() => {
      setLoadingStateText(phrases[i % phrases.length]);
      i++;
    }, 2400);
    return () => clearInterval(interval);
  }, [isLoading]);

  // Handle Feeling Toggle
  const toggleFeeling = (feeling: string) => {
    setSelectedFeelings(prev =>
      prev.includes(feeling)
        ? prev.filter(f => f !== feeling)
        : [...prev, feeling]
    );
  };

  // Helper to load example drafts
  const handleLoadExample = (ex: typeof EXAMPLE_THOUGHTS[0]) => {
    setThought(ex.text);
    setSelectedFeelings(ex.feelings);
  };

  // Submit thought for reframing
  const handleAnalyzeThought = async () => {
    if (!thought.trim()) return;
    setIsLoading(true);
    setErrorMsg(null);
    setStep(3);
    setLoadingStateText('Centering focal point...');

    try {
      const response = await fetch('/api/reframe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ thought })
      });

      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(errData.error || `Server returned error status ${response.status}`);
      }

      const data: ReframeResponse = await response.json();
      setAiResponse(data);
      setStep(4);
      setShatteredDistortions([]);
      setSelectedDistortion(data.distortions[0] || null);
      setChosenReframingText(data.reframings[0]?.text || '');
    } catch (err: any) {
      console.warn('AI analysis request failed. Falling back to Sandbox Mode.', err);
      // Trigger elegant user-friendly sandbox fallback so user doesn't hit a dead end!
      setSandboxMode(true);
      setTimeout(() => {
        // Formulate a beautiful, personalized CBT analysis locally
        const simulatedDistortions: Distortion[] = [];
        if (thought.toLowerCase().includes('never') || thought.toLowerCase().includes('always') || thought.toLowerCase().includes('anything')) {
          simulatedDistortions.push({
            name: "Overgeneralization",
            explanation: "Labeling multiple events under a sweeping negative conclusion using absolute terms like 'never' or 'always'."
          });
        }
        if (thought.toLowerCase().includes('won\'t') || thought.toLowerCase().includes('going to') || thought.toLowerCase().includes('prediction')) {
          simulatedDistortions.push({
            name: "Fortune Telling",
            explanation: "Over-confidently predicting future failures or catastrophes without evaluating immediate evidence."
          });
        }
        if (simulatedDistortions.length === 0) {
          simulatedDistortions.push({
            name: "Emotional Reasoning",
            explanation: "Taking your intense feelings (e.g., anxiety, guilt) as absolute evidence of an objective, bad reality."
          });
        }
        simulatedDistortions.push({
          name: "Catastrophizing",
          explanation: "Blowing setbacks out of proportion and expecting absolute worst-case reviews or social outcomes."
        });

        const simulatedResponse: ReframeResponse = {
          originalThought: thought,
          distortions: simulatedDistortions,
          reframings: [
            {
              type: "Balanced Factcheck",
              text: `While this negative feeling is vivid, this outcome is not an absolute fact. I have managed complex changes in the past with resilience.`
            },
            {
              type: "Self-Compassionate Check",
              text: `I am experiencing high stress right now, which magnifies mistakes. I deserve the same kindness, timing, and patience I give to close friends.`
            },
            {
              type: "Action-Oriented Reframe",
              text: `I will step back, break these worries into actionable milestones, and address what I can actually control, step-by-step.`
            }
          ]
        };

        setAiResponse(simulatedResponse);
        setStep(4);
        setShatteredDistortions([]);
        setSelectedDistortion(simulatedDistortions[0] || null);
        setChosenReframingText(simulatedResponse.reframings[0]?.text || '');
      }, 3500); // realistic thinking timing
    } finally {
      setIsLoading(false);
    }
  };

  // Shatter action
  const handleDistortionShatter = (distName: string) => {
    setIsShatterAnimated(true);
    setTimeout(() => {
      setShatteredDistortions(prev => [...prev, distName]);
      setIsShatterAnimated(false);
    }, 600);
  };

  // Complete and save journal entry
  const handleSaveToVault = () => {
    if (!aiResponse) return;

    const newEntry: JournalEntry = {
      id: `entry-${Date.now()}`,
      date: new Date().toISOString(),
      moodBefore,
      moodAfter,
      feelings: selectedFeelings.length > 0 ? selectedFeelings : ['Unspecified'],
      originalThought: thought,
      detectedDistortions: aiResponse.distortions,
      allReframings: aiResponse.reframings,
      chosenReframing: chosenReframingText,
      notes: customJournalNotes.trim() || undefined
    };

    setEntries(prev => [newEntry, ...prev]);
    
    // Reset flow
    setStep(1);
    setThought('');
    setSelectedFeelings([]);
    setMoodBefore(3);
    setMoodAfter(4);
    setCustomJournalNotes('');
    setAiResponse(null);
    setSandboxMode(false);
    
    // Hop to vault
    setActiveTab('vault');
  };

  const handleDeleteEntry = (id: string) => {
    if (window.confirm('Delete this entry permanently from your private storage?')) {
      setEntries(prev => prev.filter(e => e.id !== id));
    }
  };

  // Filter & Search Logic
  const filteredEntries = entries.filter(e => {
    const textMatch =
      e.originalThought.toLowerCase().includes(searchQuery.toLowerCase()) ||
      e.chosenReframing.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (e.notes || '').toLowerCase().includes(searchQuery.toLowerCase());

    const distortionMatch =
      filterDistortion === 'All' ||
      e.detectedDistortions.some(d => d.name === filterDistortion);

    const feelingMatch =
      filterFeeling === 'All' ||
      e.feelings.includes(filterFeeling);

    return textMatch && distortionMatch && feelingMatch;
  });

  // Extract master lists for filters
  const allAvailableDistortions = Array.from(
    new Set(entries.flatMap(e => e.detectedDistortions.map(d => d.name)))
  );
  const allAvailableFeelings = Array.from(
    new Set(entries.flatMap(e => e.feelings))
  );

  // Insights / Analytics calculations
  const totalEntries = entries.length;
  const moodImprovementStats = entries.reduce(
    (acc, next) => {
      const shift = next.moodAfter - next.moodBefore;
      if (shift > 0) acc.improved++;
      acc.totalShift += shift;
      return acc;
    },
    { improved: 0, totalShift: 0 }
  );

  const averageShift = totalEntries > 0 ? (moodImprovementStats.totalShift / totalEntries).toFixed(1) : '0';

  // Format Recharts linear trend
  const chartData = [...entries]
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
    .map(e => ({
      date: new Date(e.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }),
      'Mood Before': e.moodBefore,
      'Mood After': e.moodAfter,
      improvement: e.moodAfter - e.moodBefore
    }));

  // Format Recharts distortion metric
  const distortionMetrics = entries.flatMap(e => e.detectedDistortions.map(d => d.name));
  const countsMap = distortionMetrics.reduce((acc, next) => {
    acc[next] = (acc[next] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const barChartData = Object.entries(countsMap)
    .map(([name, count]) => ({ name, count: count as number }))
    .sort((a, b) => b.count - a.count);

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col font-sans selection:bg-amber-400/20 selection:text-amber-200" id="mindmirror-app">
      {/* Background Ambience */}
      <div className="absolute top-0 left-1/4 w-96 h-96 bg-amber-500/5 rounded-full filter blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-rose-500/5 rounded-full filter blur-3xl pointer-events-none" />

      {/* Header */}
      <header className="border-b border-zinc-900 bg-zinc-950/80 backdrop-blur-md sticky top-0 z-50 px-4 py-3.5 transition-all">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-gradient-to-tr from-amber-500 to-rose-500 p-[1px] flex items-center justify-center shadow-lg shadow-amber-500/10">
              <div className="h-full w-full rounded-full bg-zinc-950 flex items-center justify-center">
                <Brain className="h-5.5 w-5.5 text-amber-300" />
              </div>
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-xl font-semibold tracking-tight text-white font-display">MindMirror</h1>
                <span className="text-[10px] uppercase font-bold tracking-wider px-1.5 py-0.5 bg-amber-400/10 text-amber-300 rounded border border-amber-400/20">CBT Journal</span>
              </div>
              <p className="text-xs text-zinc-400">Cognitive Reframing & Metacognitive Wellness</p>
            </div>
          </div>

          {/* Navigation Controls */}
          <nav className="flex items-center gap-1.5 bg-zinc-900/60 p-1 rounded-full border border-zinc-800">
            <button
              id="tab-reframe"
              onClick={() => setActiveTab('reframe')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-medium transition ${
                activeTab === 'reframe'
                  ? 'bg-amber-400 text-zinc-950 font-semibold shadow'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <Sparkles className="h-3.5 w-3.5" />
              <span>Reframing Sanctuary</span>
            </button>
            <button
              id="tab-vault"
              onClick={() => setActiveTab('vault')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-medium transition ${
                activeTab === 'vault'
                  ? 'bg-amber-400 text-zinc-950 font-semibold shadow'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <History className="h-3.5 w-3.5" />
              <span>Compassion Vault {entries.length > 0 && `(${entries.length})`}</span>
            </button>
            <button
              id="tab-landscape"
              onClick={() => setActiveTab('landscape')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-medium transition ${
                activeTab === 'landscape'
                  ? 'bg-amber-400 text-zinc-950 font-semibold shadow'
                  : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              <BarChart2 className="h-3.5 w-3.5" />
              <span>Inner Landscape</span>
            </button>
          </nav>
        </div>
      </header>

      {/* Main Container */}
      <main className="flex-1 max-w-5xl w-full mx-auto px-4 py-8 relative">
        <AnimatePresence mode="wait">
          {/* TAB 1: REFRAMING SANCTUARY FLOW */}
          {activeTab === 'reframe' && (
            <motion.div
              key="reframe-tab"
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.3 }}
              className="space-y-6"
            >
              {/* STEP 1: EMOTIONAL TEMPERATURE & PRE-CHECK */}
              {step === 1 && (
                <div className="max-w-2xl mx-auto bg-zinc-900/40 border border-zinc-800 p-6 rounded-2xl backdrop-blur-md space-y-6 shadow-xl" id="flow-step-1">
                  <div className="text-center space-y-2">
                    <span className="text-xs uppercase text-amber-300 font-semibold tracking-widest block">Phase I: Sentiment Check</span>
                    <h2 className="text-2xl font-semibold text-white">How is your mind feeling right now?</h2>
                    <p className="text-sm text-zinc-400 max-w-md mx-auto">
                      Let us calibrate the mirror. Tune in to your internal landscape before we analyze automatic thoughts.
                    </p>
                  </div>

                  {/* Slider and Smiley Indicators */}
                  <div className="space-y-4 pt-2">
                    <div className="flex justify-between items-center text-4xl max-w-md mx-auto h-12">
                      <button
                        onClick={() => setMoodBefore(1)}
                        className={`transition-all transform hover:scale-125 ${moodBefore === 1 ? 'scale-125 saturate-100 filter drop-shadow-[0_0_8px_rgba(239,68,68,0.3)]' : 'opacity-40 grayscale hover:opacity-75'}`}
                        title="Very Distressed"
                      >
                        😞
                      </button>
                      <button
                        onClick={() => setMoodBefore(2)}
                        className={`transition-all transform hover:scale-125 ${moodBefore === 2 ? 'scale-125 saturate-100 filter drop-shadow-[0_0_8px_rgba(245,158,11,0.3)]' : 'opacity-40 grayscale hover:opacity-75'}`}
                        title="Somewhat Distressed"
                      >
                        😟
                      </button>
                      <button
                        onClick={() => setMoodBefore(3)}
                        className={`transition-all transform hover:scale-125 ${moodBefore === 3 ? 'scale-125 saturate-100 filter drop-shadow-[0_0_8px_rgba(212,212,216,0.3)]' : 'opacity-40 grayscale hover:opacity-75'}`}
                        title="Neutral / Heavy"
                      >
                        😐
                      </button>
                      <button
                        onClick={() => setMoodBefore(4)}
                        className={`transition-all transform hover:scale-125 ${moodBefore === 4 ? 'scale-125 saturate-100 filter drop-shadow-[0_0_8px_rgba(52,211,153,0.3)]' : 'opacity-40 grayscale hover:opacity-75'}`}
                        title="Slightly Grounded"
                      >
                        🙂
                      </button>
                      <button
                        onClick={() => setMoodBefore(5)}
                        className={`transition-all transform hover:scale-125 ${moodBefore === 5 ? 'scale-125 saturate-100 filter drop-shadow-[0_0_8px_rgba(16,185,129,0.3)]' : 'opacity-40 grayscale hover:opacity-75'}`}
                        title="Grounded & Clear"
                      >
                        😊
                      </button>
                    </div>

                    <div className="bg-zinc-950 p-4 rounded-xl text-center border border-zinc-900">
                      <div className="text-sm font-semibold text-zinc-200">
                        {moodBefore === 1 && "😞 Severe Distress / Overwhelmed"}
                        {moodBefore === 2 && "😟 Moderate Worry / Anxiety"}
                        {moodBefore === 3 && "😐 Neutral / Numb or Indifferent"}
                        {moodBefore === 4 && "🙂 Slightly Clear / Navigating Well"}
                        {moodBefore === 5 && "😊 Grounded / Compassionate State"}
                      </div>
                      <p className="text-xs text-zinc-500 mt-1">CBT calibration baseline value: {moodBefore} / 5</p>
                    </div>
                  </div>

                  {/* Feeling Tags multiselect */}
                  <div className="space-y-3">
                    <label className="text-xs font-semibold uppercase text-zinc-400 tracking-wider">Select specific feeling tones:</label>
                    <div className="flex flex-wrap gap-2">
                      {PRESET_FEELINGS.map(curr => {
                        const active = selectedFeelings.includes(curr.label);
                        return (
                          <button
                            key={curr.label}
                            onClick={() => toggleFeeling(curr.label)}
                            className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition transform duration-150 active:scale-95 ${
                              active
                                ? 'bg-rose-500/10 border-rose-400 text-rose-300'
                                : 'bg-zinc-950/60 border-zinc-800 hover:border-zinc-700 text-zinc-300'
                            }`}
                          >
                            {curr.label}
                          </button>
                        );
                      })}
                    </div>
                  </div>

                  <div className="pt-2 flex justify-end">
                    <button
                      onClick={() => setStep(2)}
                      className="px-6 py-2.5 bg-amber-400 text-zinc-950 rounded-xl text-xs font-semibold hover:bg-amber-300 transition flex items-center gap-2 group cursor-pointer shadow-lg shadow-amber-400/10"
                    >
                      <span>Continue to Thought Entry</span>
                      <ArrowRight className="h-3.5 w-3.5 group-hover:translate-x-1 transition-transform" />
                    </button>
                  </div>
                </div>
              )}

              {/* STEP 2: THE THOUGHT BLOCK ENTRY */}
              {step === 2 && (
                <div className="max-w-2xl mx-auto bg-zinc-900/40 border border-zinc-800 p-6 rounded-2xl backdrop-blur-md space-y-6 shadow-xl" id="flow-step-2">
                  <div className="flex items-center justify-between">
                    <button
                      onClick={() => setStep(1)}
                      className="text-xs text-zinc-400 hover:text-zinc-200 flex items-center gap-1.5"
                    >
                      <span>← Back to check-in</span>
                    </button>
                    <span className="text-xs uppercase text-amber-300 font-semibold tracking-widest">Phase II: Automatic Thoughts</span>
                  </div>

                  <div className="space-y-2">
                    <h2 className="text-2xl font-semibold text-white">Let us hold the thought up to the mirror</h2>
                    <p className="text-sm text-zinc-400">
                      When we experience stress, our minds draft sudden, cruel "automatic negative thoughts" that skew real-world perspectives. Pour it out below with absolute honesty.
                    </p>
                  </div>

                  {/* Thought input box */}
                  <div className="space-y-2">
                    <textarea
                      value={thought}
                      onChange={(e) => setThought(e.target.value)}
                      placeholder="I can never get this assignment done, I am failing at everything and everyone is better than me..."
                      className="w-full h-32 px-4 py-3 text-sm bg-zinc-950 text-zinc-100 rounded-xl border border-zinc-800 focus:border-amber-400 focus:outline-none focus:ring-1 focus:ring-amber-400 transition placeholder-zinc-600 resize-none font-sans"
                    />
                    <div className="flex justify-between items-center text-xs text-zinc-500">
                      <span>Be gentle. Privacy is 100% client-side local saving.</span>
                      <span>{thought.length} characters</span>
                    </div>
                  </div>

                  {/* Clickable examples helper */}
                  <div className="space-y-3">
                    <div className="flex items-center gap-1.5 text-xs font-semibold uppercase text-zinc-400 tracking-wider">
                      <Info className="h-3.5 w-3.5 text-amber-300" />
                      <span>Stuck? Try practicing with these real patterns:</span>
                    </div>
                    <div className="space-y-2">
                      {EXAMPLE_THOUGHTS.map((ex, idx) => (
                        <button
                          key={idx}
                          onClick={() => handleLoadExample(ex)}
                          className="w-full text-left p-3 rounded-lg bg-zinc-950/60 border border-zinc-900 hover:border-zinc-800 text-xs text-zinc-300 transition hover:bg-zinc-900/40 flex items-start gap-2 group"
                        >
                          <ChevronRight className="h-3.5 w-3.5 text-amber-400 mt-0.5 group-hover:translate-x-0.5 transition-transform shrink-0" />
                          <span className="italic">"{ex.text.slice(0, 95)}..."</span>
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="pt-2 flex justify-between items-center">
                    <div className="flex items-center gap-2 text-xs text-rose-300">
                      {selectedFeelings.length > 0 && (
                        <span>Feelings locked: {selectedFeelings.slice(0, 2).join(', ')} {selectedFeelings.length > 2 && `+${selectedFeelings.length - 2}`}</span>
                      )}
                    </div>
                    <button
                      onClick={handleAnalyzeThought}
                      disabled={!thought.trim()}
                      className={`px-6 py-2.5 rounded-xl text-xs font-semibold transition flex items-center gap-2 shadow-lg ${
                        thought.trim()
                          ? 'bg-gradient-to-r from-amber-400 to-amber-500 text-zinc-950 hover:brightness-110 active:scale-95 cursor-pointer shadow-amber-400/10'
                          : 'bg-zinc-800 text-zinc-500 cursor-not-allowed'
                      }`}
                    >
                      <Sparkles className="h-3.5 w-3.5 animate-pulse" />
                      <span>Hold Up To MindMirror</span>
                    </button>
                  </div>
                </div>
              )}

              {/* STEP 3: PROCESSING / LOADING SCREEN */}
              {step === 3 && (
                <div className="max-w-md mx-auto py-16 text-center space-y-6 bg-zinc-900/40 border border-zinc-800 p-8 rounded-2xl backdrop-blur-md shadow-xl" id="flow-step-3">
                  <div className="relative mx-auto h-24 w-24">
                    {/* Mirror circular glow framing */}
                    <div className="absolute inset-0 rounded-full border-2 border-dashed border-amber-300/40 animate-spin" style={{ animationDuration: '15s' }} />
                    <div className="absolute inset-2 rounded-full border-2 border-amber-400/20 animate-pulse" />
                    <div className="absolute inset-4 rounded-full bg-zinc-900 flex items-center justify-center border border-zinc-800 shadow-inner">
                      <Brain className="h-8 w-8 text-amber-300 animate-bounce" />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <h3 className="text-lg font-semibold text-white">Reflecting in MindMirror</h3>
                    <p className="text-xs text-zinc-400 max-w-xs mx-auto">
                      "We do not see things as they are, we see them as we are."
                    </p>
                  </div>

                  {/* Changing loading statements */}
                  <div className="bg-zinc-950 py-3 px-4 rounded-xl border border-zinc-900 text-xs font-semibold text-amber-200/90 animate-pulse min-h-[46px] flex items-center justify-center">
                    {loadingStateText}
                  </div>

                  <p className="text-[10px] text-zinc-500">
                    CBT Analysis uses a local private sandbox to process safety-first insights. Your data respects deep therapeutic confidentiality.
                  </p>
                </div>
              )}

              {/* STEP 4: INTERACTIVE SHATTERING & REFRAMING PANEL */}
              {step === 4 && aiResponse && (
                <div className="space-y-6" id="flow-step-4">
                  {/* Top Summary Banner */}
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                    {/* Interactive Distortion Mirror Column */}
                    <div className="col-span-1 lg:col-span-5 bg-zinc-900/40 border border-zinc-800 p-6 rounded-2xl backdrop-blur-md flex flex-col justify-between shadow-xl min-h-[450px]">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3">
                          <span className="text-xs font-bold uppercase tracking-wider text-rose-300">1. Original Thought Traps</span>
                          <span className="text-[10px] uppercase font-bold tracking-wider px-1.5 py-0.5 bg-zinc-950 text-zinc-400 rounded border border-zinc-800">CBT Mirror deconstruct</span>
                        </div>

                        {/* Interactive "Mirror glass" showcasing Original Thought */}
                        <div className="relative bg-gradient-to-b from-zinc-900 to-zinc-950 p-4 rounded-xl border border-zinc-800 shadow-inner overflow-hidden min-h-[110px] flex items-center justify-center">
                          {/* Grid line grid overlay to represent physical mirror panel */}
                          <div className="absolute inset-0 bg-grid-white/[0.02] pointer-events-none" />
                          <div className="absolute left-0 top-0 h-full w-full bg-gradient-to-r from-transparent via-white/[0.03] to-transparent transform -translate-x-full animate-[shimmer_5s_infinite]" />

                          <p className={`text-sm italic relative text-center px-4 ${shatteredDistortions.length === aiResponse.distortions.length ? 'scale-90 opacity-20 line-through text-zinc-600 transition-all duration-700' : 'text-zinc-200'}`}>
                            "{aiResponse.originalThought}"
                          </p>

                          {shatteredDistortions.length === aiResponse.distortions.length && (
                            <div className="absolute inset-0 flex items-center justify-center bg-zinc-950/70 backdrop-blur-[1px]">
                              <span className="text-xs uppercase tracking-widest font-bold text-emerald-400 bg-emerald-950/60 border border-emerald-500/20 px-3 py-1.5 rounded-lg flex items-center gap-1.5 animate-bounce">
                                <CheckCircle2 className="h-4 w-4" />
                                <span>Mirror Cleared</span>
                              </span>
                            </div>
                          )}
                        </div>

                        {/* Helper instructions */}
                        <div className="space-y-3">
                          <p className="text-xs font-semibold text-zinc-400">
                            {shatteredDistortions.length < aiResponse.distortions.length
                              ? "Select and shatter the cognitive illusions holding your perspective hostaged:"
                              : "All identified illusions have been seen through. Excellent job."}
                          </p>

                          {/* List of Distortions */}
                          <div className="space-y-2.5">
                            {aiResponse.distortions.map((dist, idx) => {
                              const isShattered = shatteredDistortions.includes(dist.name);
                              const isActive = selectedDistortion?.name === dist.name;

                              return (
                                <div
                                  key={idx}
                                  onClick={() => !isShattered && setSelectedDistortion(dist)}
                                  className={`p-3 rounded-xl border transition text-left cursor-pointer select-none relative overflow-hidden ${
                                    isShattered
                                      ? 'bg-zinc-950/30 border-zinc-900/60 text-zinc-600 cursor-default opacity-45'
                                      : isActive
                                      ? 'bg-rose-500/5 border-rose-500/80 shadow-lg shadow-rose-500/5'
                                      : 'bg-zinc-950/60 border-zinc-900 hover:border-zinc-800'
                                  }`}
                                >
                                  <div className="flex items-start justify-between gap-2">
                                    <div>
                                      <h4 className={`text-xs font-bold tracking-tight ${isShattered ? 'line-through text-zinc-500' : isActive ? 'text-rose-300 font-semibold' : 'text-zinc-200'}`}>
                                        {dist.name}
                                      </h4>
                                      {!isShattered && isActive && (
                                        <p className="text-[11px] text-zinc-400 mt-1.5 leading-relaxed">
                                          {dist.explanation}
                                        </p>
                                      )}
                                    </div>

                                    {!isShattered ? (
                                      <button
                                        onClick={(e) => {
                                          e.stopPropagation();
                                          handleDistortionShatter(dist.name);
                                        }}
                                        className="text-[10px] font-bold text-rose-300 hover:text-rose-200 uppercase bg-rose-400/10 hover:bg-rose-400/20 px-2 py-1 rounded border border-rose-400/20 select-none cursor-pointer"
                                      >
                                        Shatter
                                      </button>
                                    ) : (
                                      <span className="text-[10px] font-semibold text-emerald-400 uppercase tracking-widest bg-emerald-400/10 border border-emerald-400/20 px-2.5 py-0.5 rounded">
                                        Seen Through
                                      </span>
                                    )}
                                  </div>

                                  {/* Glass breakdown animation overlay */}
                                  {isActive && isShatterAnimated && !isShattered && (
                                    <div className="absolute inset-0 bg-rose-400/15 animate-ping pointer-events-none" />
                                  )}
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      </div>

                      {sandboxMode && (
                        <div className="mt-4 p-2.5 rounded-lg bg-amber-400/5 border border-amber-400/20 text-[11px] text-amber-200 bg-zinc-950/60 flex items-start gap-2">
                          <AlertCircle className="h-4 w-4 text-amber-400 shrink-0 mt-0.5" />
                          <span>We have loaded our smart offline CBT dictionary engine dynamically. Feel free to fully interact with these reframing paths!</span>
                        </div>
                      )}
                    </div>

                    {/* Choose Reframe Options & Outcome Column */}
                    <div className="col-span-1 lg:col-span-7 bg-zinc-900/40 border border-zinc-800 p-6 rounded-2xl backdrop-blur-md flex flex-col justify-between shadow-xl min-h-[450px]">
                      <div className="space-y-4">
                        <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3">
                          <span className="text-xs font-bold uppercase tracking-wider text-amber-300">2. Shattered Truths (Reframed Alternatives)</span>
                          <span className="text-xs text-zinc-400">Step 4 of 5</span>
                        </div>

                        <div className="space-y-3">
                          <p className="text-xs font-semibold text-zinc-400">
                            Which alternative, realistic perspective resonates most to engrave inside your emotional vault?
                          </p>

                          {/* Reframing Selection list */}
                          <div className="space-y-3">
                            {aiResponse.reframings.map((reframe, idx) => {
                              const isSelected = chosenReframingText === reframe.text;
                              return (
                                <div
                                  key={idx}
                                  onClick={() => setChosenReframingText(reframe.text)}
                                  className={`p-4 rounded-xl border text-left cursor-pointer transition relative group ${
                                    isSelected
                                      ? 'bg-amber-400/5 border-amber-400 text-amber-100 shadow-md shadow-amber-400/5'
                                      : 'bg-zinc-950/60 border-zinc-900 hover:border-zinc-800 text-zinc-300'
                                  }`}
                                >
                                  <div className="flex items-start gap-3">
                                    <div className={`mt-0.5 shrink-0 h-4 w-4 rounded-full border-2 flex items-center justify-center transition-all ${
                                      isSelected ? 'border-amber-400 bg-amber-400' : 'border-zinc-700'
                                    }`}>
                                      {isSelected && <div className="h-1.5 w-1.5 bg-zinc-950 rounded-full" />}
                                    </div>
                                    <div className="space-y-1">
                                      <span className={`text-[10px] uppercase font-bold tracking-widest ${isSelected ? 'text-amber-300' : 'text-zinc-500'}`}>
                                        {reframe.type}
                                      </span>
                                      <p className="text-xs leading-relaxed font-medium">
                                        "{reframe.text}"
                                      </p>
                                    </div>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>

                        {/* Optional post-journal check in */}
                        <div className="space-y-3 pt-2">
                          <div className="flex flex-col sm:flex-row sm:items-center gap-4 border-t border-zinc-800/80 pt-4">
                            <div className="space-y-1 shrink-0">
                              <label className="text-xs font-bold uppercase tracking-wider text-emerald-300 block">Rating after reframing:</label>
                              <span className="text-[10px] text-zinc-500">Gauge if reframing softened the distress level.</span>
                            </div>

                            {/* Post Mood Rating icons */}
                            <div className="flex items-center gap-2">
                              {[1, 2, 3, 4, 5].map((val) => {
                                const emoji = val === 1 ? '😞' : val === 2 ? '😟' : val === 3 ? '😐' : val === 4 ? '🙂' : '😊';
                                return (
                                  <button
                                    key={val}
                                    onClick={() => setMoodAfter(val)}
                                    className={`p-2 rounded-lg text-lg transition duration-150 border active:scale-95 ${
                                      moodAfter === val
                                        ? 'bg-emerald-500/10 border-emerald-400 text-emerald-300 transform scale-110 shadow-sm shadow-emerald-400/10'
                                        : 'bg-zinc-950/60 border-zinc-900 grayscale opacity-45 hover:opacity-80 hover:grayscale-0'
                                    }`}
                                    title={`Rating ${val}`}
                                  >
                                    {emoji}
                                  </button>
                                );
                              })}
                            </div>
                          </div>

                          <div className="space-y-1 pt-1">
                            <label className="text-xs font-bold uppercase tracking-wider text-zinc-400 block">Any supplementary notes? (Optional)</label>
                            <input
                              type="text"
                              value={customJournalNotes}
                              onChange={(e) => setCustomJournalNotes(e.target.value)}
                              placeholder="e.g. Talked it over, scheduled a structured task block to resolve anxiety..."
                              className="w-full px-3.5 py-2 text-xs bg-zinc-950 text-zinc-300 rounded-lg border border-zinc-900 focus:border-amber-400 focus:outline-none transition placeholder-zinc-700"
                            />
                          </div>
                        </div>
                      </div>

                      <div className="pt-6 border-t border-zinc-800/80 flex justify-between items-center mt-4">
                        <button
                          onClick={() => {
                            if (window.confirm("Abandon current reframing analysis? Data will not be finalized.")) {
                              setStep(1);
                              setThought('');
                              setSelectedFeelings([]);
                              setAiResponse(null);
                            }
                          }}
                          className="text-xs text-zinc-500 hover:text-zinc-300 flex items-center gap-1 cursor-pointer transition"
                        >
                          <RotateCcw className="h-3.5 w-3.5" />
                          <span>Start Over</span>
                        </button>

                        <button
                          onClick={handleSaveToVault}
                          className="px-6 py-2.5 bg-gradient-to-r from-amber-400 to-amber-500 text-zinc-950 rounded-xl text-xs font-bold hover:brightness-110 transition flex items-center gap-2 shadow-lg shadow-amber-400/10 active:scale-95 cursor-pointer"
                        >
                          <Heart className="h-3.5 w-3.5 text-zinc-950 fill-zinc-950" />
                          <span>Engrave in Vault</span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </motion.div>
          )}

          {/* TAB 2: COMPASSION VAULT (HISTORY LOG) */}
          {activeTab === 'vault' && (
            <motion.div
              key="vault-tab"
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.3 }}
              className="space-y-6"
            >
              {/* Vault Intro & Metric */}
              <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-6 backdrop-blur-md flex flex-col md:flex-row items-center justify-between gap-6 shadow-xl">
                <div className="space-y-1.5 text-center md:text-left">
                  <span className="text-xs uppercase text-amber-300 font-semibold tracking-widest block">Metacognitive Records</span>
                  <h2 className="text-2xl font-semibold text-white">Your Vault of Hard-Won Truths</h2>
                  <p className="text-sm text-zinc-400 max-w-lg">
                    Revisit these entries whenever automatic distressing thoughts emerge. They represent your real, logic-tested truths in times of struggle.
                  </p>
                </div>
                <div className="flex gap-4 shrink-0">
                  <div className="bg-zinc-950 px-4 py-3 rounded-xl border border-zinc-900 text-center min-w-[100px]">
                    <span className="text-2xl font-bold text-amber-300">{entries.length}</span>
                    <p className="text-[10px] text-zinc-500 uppercase font-semibold mt-0.5">Cleared Thoughts</p>
                  </div>
                  <div className="bg-zinc-950 px-4 py-3 rounded-xl border border-zinc-900 text-center min-w-[100px]">
                    <span className="text-2xl font-bold text-emerald-400">{averageShift}</span>
                    <p className="text-[10px] text-zinc-500 uppercase font-semibold mt-0.5">Avg Mood Boost</p>
                  </div>
                </div>
              </div>

              {/* Filters Panel */}
              <div className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-4 backdrop-blur-md grid grid-cols-1 md:grid-cols-12 gap-4 items-center">
                {/* Search Box */}
                <div className="col-span-1 md:col-span-5 relative">
                  <Search className="absolute left-3.5 top-2.5 h-4 w-4 text-zinc-500" />
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search past thoughts or reframings..."
                    className="w-full pl-10 pr-4 py-2 text-xs bg-zinc-950 text-zinc-200 rounded-xl border border-zinc-800 focus:border-amber-400 focus:outline-none transition placeholder-zinc-600"
                  />
                </div>

                {/* Filter Distortion */}
                <div className="col-span-1 md:col-span-3">
                  <select
                    value={filterDistortion}
                    onChange={(e) => setFilterDistortion(e.target.value)}
                    className="w-full px-3 py-2 text-xs bg-zinc-950 text-zinc-300 rounded-xl border border-zinc-800 focus:border-amber-400 focus:outline-none focus:ring-1 focus:ring-amber-400"
                  >
                    <option value="All">All Illusions ({allAvailableDistortions.length})</option>
                    {allAvailableDistortions.map((dist, idx) => (
                      <option key={idx} value={dist}>{dist}</option>
                    ))}
                  </select>
                </div>

                {/* Filter Feeling */}
                <div className="col-span-1 md:col-span-3">
                  <select
                    value={filterFeeling}
                    onChange={(e) => setFilterFeeling(e.target.value)}
                    className="w-full px-3 py-2 text-xs bg-zinc-950 text-zinc-300 rounded-xl border border-zinc-800 focus:border-amber-400 focus:outline-none focus:ring-1 focus:ring-amber-400"
                  >
                    <option value="All">All Emotions ({allAvailableFeelings.length})</option>
                    {allAvailableFeelings.map((feel, idx) => (
                      <option key={idx} value={feel}>{feel}</option>
                    ))}
                  </select>
                </div>

                {/* Reset button */}
                <button
                  onClick={() => {
                    setSearchQuery('');
                    setFilterDistortion('All');
                    setFilterFeeling('All');
                  }}
                  className="col-span-1 border border-zinc-800 p-2 text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 rounded-xl text-center cursor-pointer transition"
                  title="Reset Filters"
                >
                  Clear
                </button>
              </div>

              {/* Entries Grid list */}
              <div className="space-y-4">
                {filteredEntries.length === 0 ? (
                  <div className="text-center py-16 bg-zinc-900/20 border border-zinc-800/50 rounded-2xl backdrop-blur-sm">
                    <History className="h-10 w-10 text-zinc-700 mx-auto mb-3 animate-pulse" />
                    <p className="text-sm font-semibold text-zinc-400">No matching meta records found.</p>
                    <p className="text-xs text-zinc-500 mt-1">Try softening search filters or record a new reframed check-in!</p>
                  </div>
                ) : (
                  filteredEntries.map((entry) => {
                    const moodDifference = entry.moodAfter - entry.moodBefore;
                    const preEmoji = entry.moodBefore === 1 ? '😞' : entry.moodBefore === 2 ? '😟' : entry.moodBefore === 3 ? '😐' : entry.moodBefore === 4 ? '🙂' : '😊';
                    const postEmoji = entry.moodAfter === 1 ? '😞' : entry.moodAfter === 2 ? '😟' : entry.moodAfter === 3 ? '😐' : entry.moodAfter === 4 ? '🙂' : '😊';

                    return (
                      <div
                        key={entry.id}
                        className="bg-zinc-900/40 border border-zinc-800 rounded-2xl p-5 backdrop-blur-md space-y-4 hover:border-zinc-700/80 transition shadow hover:shadow-lg"
                      >
                        {/* Entry Header indicators */}
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-zinc-800/60 pb-3">
                          <div className="flex items-center gap-2">
                            <Calendar className="h-3.5 w-3.5 text-zinc-500" />
                            <span className="text-xs text-zinc-400 font-medium">
                              {new Date(entry.date).toLocaleString(undefined, {
                                weekday: 'short',
                                year: 'numeric',
                                month: 'short',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit'
                              })}
                            </span>
                          </div>

                          <div className="flex items-center gap-2.5">
                            {/* Sentiment rating delta display */}
                            <span className="text-xs text-zinc-400 flex items-center gap-1.5">
                              Sentiment: <span className="text-lg">{preEmoji}</span>
                              <span className="text-zinc-500">➜</span>
                              <span className="text-lg">{postEmoji}</span>
                            </span>

                            {moodDifference > 0 ? (
                              <span className="text-[10px] font-bold uppercase tracking-wider bg-emerald-400/10 border border-emerald-400/20 text-emerald-300 px-2 py-0.5 rounded">
                                +{moodDifference} Lift
                              </span>
                            ) : moodDifference === 0 ? (
                              <span className="text-[10px] font-bold uppercase tracking-wider bg-zinc-800 text-zinc-400 px-2 py-0.5 rounded">
                                Neutral
                              </span>
                            ) : (
                              <span className="text-[10px] font-bold uppercase tracking-wider bg-rose-400/10 text-rose-300 px-2 py-0.5 rounded">
                                {moodDifference} Distress
                              </span>
                            )}

                            <button
                              onClick={() => handleDeleteEntry(entry.id)}
                              className="text-zinc-600 hover:text-rose-400 p-1 rounded hover:bg-zinc-950 transition cursor-pointer"
                              title="Delete record permanently"
                            >
                              <Trash2 className="h-3.5 w-3.5" />
                            </button>
                          </div>
                        </div>

                        {/* Automatic Thought */}
                        <div className="space-y-1.5">
                          <span className="text-[10px] bg-zinc-950 text-zinc-500 border border-zinc-800 px-2 py-0.5 rounded uppercase font-bold tracking-widest inline-block select-none">
                            Automatic Thought (Raw distress)
                          </span>
                          <p className="text-sm text-zinc-400 italic line-through decoration-zinc-800 decoration-2 pl-2">
                            "{entry.originalThought}"
                          </p>
                        </div>

                        {/* Distortion tags */}
                        {entry.detectedDistortions.length > 0 && (
                          <div className="flex flex-wrap gap-1.5 items-center">
                            <span className="text-[9px] uppercase tracking-wider font-bold text-zinc-500 mr-1 select-none">Traps Detected:</span>
                            {entry.detectedDistortions.map((dist, idx) => (
                              <span
                                key={idx}
                                className="text-[10px] font-medium bg-rose-500/5 text-rose-300 border border-rose-500/20 px-2 py-0.5 rounded"
                                title={dist.explanation}
                              >
                                {dist.name}
                              </span>
                            ))}
                          </div>
                        )}

                        {/* Chosen Reframed Perspective */}
                        <div className="bg-amber-400/5 border border-amber-400/30 p-3 rounded-xl space-y-1 relative overflow-hidden">
                          {/* Left warning label line */}
                          <div className="absolute left-0 top-0 bottom-0 w-1 bg-amber-400" />
                          <div className="flex items-center gap-1.5 text-[10px] uppercase font-bold text-amber-300 tracking-wider">
                            <Heart className="h-3.5 w-3.5 fill-amber-400 text-amber-400 shrink-0" />
                            <span>Engraved Truth</span>
                          </div>
                          <p className="text-sm font-semibold text-zinc-100 pl-1 leading-relaxed">
                            "{entry.chosenReframing}"
                          </p>
                        </div>

                        {/* Notes if written */}
                        {entry.notes && (
                          <div className="text-xs text-zinc-500 bg-zinc-950 p-2.5 rounded-xl border border-zinc-900/60 leading-relaxed font-normal">
                            <span className="font-semibold text-zinc-400 block mb-0.5 text-[10px] uppercase tracking-wider">Metacognitive Notes & Actions:</span>
                            {entry.notes}
                          </div>
                        )}
                      </div>
                    );
                  })
                )}
              </div>
            </motion.div>
          )}

          {/* TAB 3: INNER LANDSCAPE (ANALYTICS & INSIGHTS) */}
          {activeTab === 'landscape' && (
            <motion.div
              key="landscape-tab"
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.3 }}
              className="space-y-6"
            >
              <div className="bg-zinc-900/40 border border-zinc-800 p-6 rounded-2xl backdrop-blur-md space-y-2 shadow-xl">
                <span className="text-xs uppercase text-amber-300 font-semibold tracking-widest block font-display">Cognitive Mapping Insights</span>
                <h2 className="text-2xl font-bold text-white">Your Emotional Inner Landscape</h2>
                <p className="text-sm text-zinc-400">
                  Observe and evaluate objective metrics regarding how active self-compassionate reframing reduces automatic anxiety and breaks long-term thought traps.
                </p>
              </div>

              {/* Statistical Bento-Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-zinc-900/40 border border-zinc-800 p-5 rounded-2xl backdrop-blur-md flex flex-col justify-between shadow-md">
                  <div className="space-y-1">
                    <span className="text-xs uppercase tracking-wider font-bold text-zinc-500">Processed Inputs</span>
                    <h3 className="text-3xl font-extrabold text-white">{totalEntries}</h3>
                  </div>
                  <p className="text-xs text-zinc-400 mt-2">Thoughts reframed and saved securely.</p>
                </div>

                <div className="bg-zinc-900/40 border border-zinc-800 p-5 rounded-2xl backdrop-blur-md flex flex-col justify-between shadow-md">
                  <div className="space-y-1">
                    <span className="text-xs uppercase tracking-wider font-bold text-zinc-500">Relief Efficiency</span>
                    <h3 className="text-3xl font-extrabold text-emerald-400">
                      {totalEntries > 0
                        ? `${Math.round((moodImprovementStats.improved / totalEntries) * 100)}%`
                        : '0%'}
                    </h3>
                  </div>
                  <p className="text-xs text-zinc-400 mt-2">Proportion of thoughts resulting in active mood lift.</p>
                </div>

                <div className="bg-zinc-900/40 border border-zinc-800 p-5 rounded-2xl backdrop-blur-md flex flex-col justify-between shadow-md">
                  <div className="space-y-1">
                    <span className="text-xs uppercase tracking-wider font-bold text-zinc-500">Avg Sentiment Boost</span>
                    <h3 className="text-3xl font-extrabold text-amber-300">+{averageShift}</h3>
                  </div>
                  <p className="text-xs text-zinc-400 mt-2">Numerical point elevation index per check-in.</p>
                </div>

                <div className="bg-zinc-900/40 border border-zinc-800 p-5 rounded-2xl backdrop-blur-md flex flex-col justify-between shadow-md">
                  <div className="space-y-1">
                    <span className="text-xs uppercase tracking-wider font-bold text-zinc-500">Self-Reflection Streak</span>
                    <h3 className="text-3xl font-extrabold text-rose-300">
                      {entries.length > 0 ? `${entries.length} days` : '0 days'}
                    </h3>
                  </div>
                  <p className="text-xs text-zinc-400 mt-2">Active cognitive vigilance momentum.</p>
                </div>
              </div>

              {totalEntries === 0 ? (
                <div className="py-16 text-center bg-zinc-900/10 border border-zinc-800/60 rounded-2xl backdrop-blur-sm">
                  <BarChart2 className="h-10 w-10 text-zinc-800 mx-auto mb-3 animate-pulse" />
                  <p className="text-sm font-semibold text-zinc-400">No sufficient entries to chart metrics yet.</p>
                  <p className="text-xs text-zinc-500 mt-1">Sunder and log a few automatic negative thoughts to map statistics here!</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                  {/* Line Chart: Mood Trend progression */}
                  <div className="col-span-1 lg:col-span-7 bg-zinc-900/40 border border-zinc-800 p-5 rounded-2xl backdrop-blur-md space-y-4 shadow-xl select-none">
                    <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3">
                      <span className="text-xs font-bold uppercase tracking-wider text-amber-300 flex items-center gap-1.5">
                        <Activity className="h-4 w-4" />
                        <span>Sentiment Check-In Progress</span>
                      </span>
                      <span className="text-[10px] text-zinc-500 font-semibold">Mood ratings: 1 (Very Distressed) to 5 (Grounded)</span>
                    </div>

                    <div className="h-72 w-full text-xs">
                      {chartData.length > 0 ? (
                        <ResponsiveContainer width="100%" height="100%">
                          <LineChart data={chartData} margin={{ top: 10, right: 10, left: -25, bottom: 5 }}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#1d1d21" />
                            <XAxis dataKey="date" stroke="#71717a" tickLine={false} />
                            <YAxis domain={[1, 5]} strict stroke="#71717a" fontSize={11} ticks={[1, 2, 3, 4, 5]} tickLine={false} />
                            <Tooltip
                              contentStyle={{ backgroundColor: '#18181b', border: '1px solid #27272a', borderRadius: '12px' }}
                              labelStyle={{ color: '#a1a1aa', fontWeight: 'bold' }}
                            />
                            <Legend verticalAlign="top" height={36} />
                            <Line type="monotone" dataKey="Mood Before" stroke="#f43f5e" strokeWidth={2.5} activeDot={{ r: 6 }} />
                            <Line type="monotone" dataKey="Mood After" stroke="#10b981" strokeWidth={2.5} activeDot={{ r: 6 }} />
                          </LineChart>
                        </ResponsiveContainer>
                      ) : (
                        <div className="h-full flex items-center justify-center text-zinc-600">Waiting for trend data entries...</div>
                      )}
                    </div>
                  </div>

                  {/* Horizontal Bar Chart: Key automatic thought traps breakdown */}
                  <div className="col-span-1 lg:col-span-5 bg-zinc-900/40 border border-zinc-800 p-5 rounded-2xl backdrop-blur-md space-y-4 shadow-xl select-none">
                    <div className="flex items-center justify-between border-b border-zinc-800/80 pb-3">
                      <span className="text-xs font-bold uppercase tracking-wider text-rose-300 flex items-center gap-1.5">
                        <Info className="h-4 w-4" />
                        <span>Recurring Distortion Traps</span>
                      </span>
                      <span className="text-[10px] text-zinc-500 font-medium">Cognitive category occurrences</span>
                    </div>

                    <div className="h-72 w-full text-xs">
                      {barChartData.length > 0 ? (
                        <ResponsiveContainer width="100%" height="100%">
                          <BarChart data={barChartData} layout="vertical" margin={{ top: 5, right: 10, left: 10, bottom: 5 }}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#1d1d21" horizontal={false} />
                            <XAxis type="number" stroke="#71717a" fontSize={10} tickLine={false} />
                            <YAxis dataKey="name" type="category" stroke="#e4e4e7" fontSize={9.5} width={100} tickLine={false} />
                            <Tooltip
                              contentStyle={{ backgroundColor: '#18181b', border: '1px solid #27272a', borderRadius: '12px' }}
                            />
                            <Bar dataKey="count" fill="#f43f5e" radius={[0, 4, 4, 0]}>
                              {barChartData.map((entry, index) => (
                                <Cell key={`cell-${index}`} fill={index === 0 ? '#fbbf24' : index === 1 ? '#f43f5e' : '#ec4899'} />
                              ))}
                            </Bar>
                          </BarChart>
                        </ResponsiveContainer>
                      ) : (
                        <div className="h-full flex items-center justify-center text-zinc-600">Waiting for mapping traps...</div>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {/* Cognitive Behavioral Therapy (CBT) Reference Guide panel */}
              <div className="bg-zinc-900/40 border border-[#2c2d30] hover:border-[#383a3f] transition p-6 rounded-2xl backdrop-blur-md space-y-4 shadow-xl">
                <div className="flex items-center gap-2 border-b border-zinc-850 pb-2.5">
                  <Award className="h-5 w-5 text-amber-300" />
                  <h3 className="text-sm font-bold uppercase tracking-wider text-white">Cognitive Behavioral Therapy Reference Dictionary</h3>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 text-xs">
                  <div className="space-y-1">
                    <h4 className="font-semibold text-amber-200">Catastrophizing</h4>
                    <p className="text-zinc-400 leading-relaxed">Expecting the absolute worst-case scenario over-sensibly, treating low-odds mishaps as terminal crises.</p>
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-semibold text-amber-200">All-or-Nothing Statements</h4>
                    <p className="text-zinc-400 leading-relaxed">Viewing events in black-and-white compartments. A failure in one task triggers labels of "totally useless".</p>
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-semibold text-amber-200">Mind-Reading Illusion</h4>
                    <p className="text-zinc-400 leading-relaxed">Arbitrarily assuming other people are judging or reviewing you negatively, without searching for concrete indicators.</p>
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-semibold text-rose-300">Emotional Reasoning</h4>
                    <p className="text-zinc-400 leading-relaxed">Taking your emotional distress (e.g. \"I feel incredibly guilty\") as immediate fact-proof that you committed actual errors.</p>
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-semibold text-rose-300">Overgeneralization</h4>
                    <p className="text-zinc-400 leading-relaxed">Declaring global conclusions based on a isolated incident. A single text delay prompts "they will always ignore me".</p>
                  </div>
                  <div className="space-y-1">
                    <h4 className="font-semibold text-rose-300">Should Statements</h4>
                    <p className="text-zinc-400 leading-relaxed">Torturing your mind with strict, punitive guidelines ("I should behave flawlessly"), creating deep shame when fallible.</p>
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      <footer className="border-t border-zinc-900 bg-zinc-950/40 py-6 text-center text-[11px] text-zinc-500 mt-12">
        <div className="max-w-5xl mx-auto px-4 flex flex-col md:flex-row items-center justify-between gap-4">
          <p>© 2026 MindMirror Sanctuary. Private Local Session Storage (HIPAA-aligned metadata paradigm).</p>
          <div className="flex gap-4">
            <span className="flex items-center gap-1"><Shield className="h-3 w-3 text-emerald-400" /> 100% Secure Encrypted client runtime</span>
            <span className="flex items-center gap-1"><Brain className="h-3 w-3 text-amber-300" /> Inspired by Cognitive Behavioral Neuropsychology</span>
          </div>
        </div>
      </footer>
    </div>
  );
}

// Inline animation helper
const Activity = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
  </svg>
);
